### ISSUE TITLE
document clearing of KG-Microbe graph, dumping and restoring

### ISSUE THREAD

**Issue by turbomam** [berkeleybop/metpo#101]
```SPARQL
CLEAR GRAPH <https://kg-hub.berkeleybop.io/kg-microbe/current>
```

- kg-microbe-core_20250222.nt 4.1G
- kg-microbe-core_20250222.nt.gz 222M

**Comment by turbomam** [comment]
when it's time to restore: http://portal.nersc.gov/project/m4689/kg-microbe-core_20250222.nt.gz


- kg-microbe-core_20250222.nt 4.1G
- kg-microbe-core_20250222.nt.gz 222M

**Comment by turbomam** [comment]
export the other graphs to BRF format with the web interface

**Comment by turbomam** [comment]
```yaml
version: '3.8'
services:
  graphdb:
    image: ontotext/graphdb:11.0.1
    container_name: graphdb-11
    ports:
      - "7200:7200"
    environment:
      GRAPHDB_EDITION: "free"
      JAVA_OPTS: "-Xms8g -Xmx16g"
    volumes:
      - graphdb_data:/opt/graphdb/home
    deploy:
      resources:
        limits:
          memory: 16g

volumes:
  graphdb_data:
```
