### ISSUE TITLE
get BacDive utilization types into ROBOT and OntoGPT templates

### ISSUE THREAD

**Issue by turbomam** [berkeleybop/metpo#123]
```shell
time jq -r  \
    '["value", "count"], ([.[] | .. | objects | select(has("kind of utilization tested")) | ."kind of utilization tested"] | group_by(.) | map([.[0], length])[]) | @tsv'  \
    /global/cfs/cdirs/m4689/master/kg-microbe/data/raw/bacdive_strains.json > \
    bacdive-utlizations.tsv
```

~ 30 seconds

**Comment by turbomam** [comment]
previous relationships enum:

```yaml
  RelationshipTypeEnum:
    description: Types of biological relationships between organisms and compounds
    permissible_values:
      ferments:
        description: The organism ferments the compound
      produces:
        description: The organism produces the compound
      utilizes:
        description: The organism utilizes the compound for growth or metabolism
      reduces:
        description: The organism reduces the compound
      oxidizes:
        description: The organism oxidizes the compound
      metabolizes:
        description: The organism metabolizes the compound
      grows_on:
        description: The organism grows on the compound as a substrate
      contains:
        description: The organism contains the compound as a cellular component
      does_not_ferment:
        description: The organism does not ferment the compound
      does_not_utilize:
        description: The organism does not utilize the compound
      degrades:
        description: The organism degrades the compound
      transforms:
        description: The organism transforms the compound
      converts:
        description: The organism converts the compound
      reduces_to:
        description: The organism reduces the compound to another product
```
