### ISSUE TITLE
document the KG-Micbrobe phenotype values

### ISSUE THREAD

**Issue by turbomam** [berkeleybop/metpo#99]
```sparql
select 
?o (count(?s) as ?count)
where {
    graph <https://kg-hub.berkeleybop.io/kg-microbe/current> {
        ?s <https://w3id.org/biolink/vocab/has_phenotype> ?o
    }
}
group by ?o
```

> Showing results from 0 to 116 of 116. Query took 0.7s, moments ago.

**Comment by turbomam** [comment]
```sparql
select 
?o (count(?s) as ?count)
where {
    graph <https://kg-hub.berkeleybop.io/kg-microbe/current> {
        ?s <https://w3id.org/biolink/vocab/has_phenotype> ?o .
        FILTER(strstarts(str(?o),"https://www.example.org/UNKNOWN/temp"))
    }
}
group by ?o
order by ?o
```

> Showing results from 0 to 23 of 23. Query took 0.6s, moments ago.

**Comment by turbomam** [comment]
o | count
-- | --
https://www.example.org/UNKNOWN/temp_delta:high | "844"^^xsd:integer
https://www.example.org/UNKNOWN/temp_delta:low | "271"^^xsd:integer
https://www.example.org/UNKNOWN/temp_delta:mid1 | "532"^^xsd:integer
https://www.example.org/UNKNOWN/temp_delta:mid2 | "856"^^xsd:integer
https://www.example.org/UNKNOWN/temp_delta:mid3 | "1448"^^xsd:integer
https://www.example.org/UNKNOWN/temp_opt:high | "300"^^xsd:integer
https://www.example.org/UNKNOWN/temp_opt:low | "200"^^xsd:integer
https://www.example.org/UNKNOWN/temp_opt:mid1 | "486"^^xsd:integer
https://www.example.org/UNKNOWN/temp_opt:mid2 | "2214"^^xsd:integer
https://www.example.org/UNKNOWN/temp_opt:mid3 | "395"^^xsd:integer
https://www.example.org/UNKNOWN/temp_opt:mid4 | "715"^^xsd:integer
https://www.example.org/UNKNOWN/temp_opt:very_low | "19"^^xsd:integer
https://www.example.org/UNKNOWN/temp_range:high | "1248"^^xsd:integer
https://www.example.org/UNKNOWN/temp_range:low | "2760"^^xsd:integer
https://www.example.org/UNKNOWN/temp_range:mid1 | "3113"^^xsd:integer
https://www.example.org/UNKNOWN/temp_range:mid2 | "3544"^^xsd:integer
https://www.example.org/UNKNOWN/temp_range:mid3 | "3082"^^xsd:integer
https://www.example.org/UNKNOWN/temp_range:mid4 | "3052"^^xsd:integer
https://www.example.org/UNKNOWN/temp_range:very_low | "1476"^^xsd:integer
https://www.example.org/UNKNOWN/temperature:hyperthermophilic | "263"^^xsd:integer
https://www.example.org/UNKNOWN/temperature:mesophilic | "26633"^^xsd:integer
https://www.example.org/UNKNOWN/temperature:psychrophilic | "1406"^^xsd:integer
https://www.example.org/UNKNOWN/temperature:thermophilic | "1942"^^xsd:integer

**Comment by turbomam** [comment]
### assertions

```sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select 
?o (count(?s) as ?count)
where {
    graph <https://kg-hub.berkeleybop.io/kg-microbe/current> {
        ?x rdf:subject ?s ;
        rdf:predicate <https://w3id.org/biolink/vocab/has_phenotype> ;
        rdf:object ?o .
        FILTER(strstarts(str(?o),"https://www.example.org/UNKNOWN/temp"))
    }
}
group by ?o
order by ?o
```

> Showing results from 0 to 23 of 23. Query took 1.6s, moments ago.

sames counts as above

**Comment by turbomam** [comment]
https://github.com/Knowledge-Graph-Hub/kg-microbe/blob/master/schemas/trait_condensed.yaml

```yaml
classes:
  bacteria-archaea-traits:
    - range_tmp
slots:
  range_tmp:
    range: range_tmp_enum
    examples:
      value: NA
  range_tmp_enum:
    ## TODO: the mappings below are automated
    permissible_values:
      mesophilic:
        description: mesophilic
        meaning: http://purl.obolibrary.org/obo/MICRO_0000111
      facultative psychrophilic:
        description: facultative psychrophilic
        meaning: http://purl.obolibrary.org/obo/MICRO_0001306
      extreme thermophilic:
        description: extreme thermophilic
        meaning: http://purl.obolibrary.org/obo/MICRO_0000118
      NA:
        description: NA
        meaning: http://purl.obolibrary.org/obo/CL_0000895
      thermophilic:
        description: thermophilic
        meaning: http://purl.obolibrary.org/obo/MICRO_0000118
      psychrotolerant:
        description: psychrotolerant
        meaning: http://purl.obolibrary.org/obo/MICRO_0001310
      thermotolerant:
        description: thermotolerant
        meaning: http://purl.obolibrary.org/obo/MICRO_0001286
      psychrophilic:
        description: psychrophilic
        meaning: http://purl.obolibrary.org/obo/MICRO_0001306
```
